config/routes.rb
Rails.application.routes.draw do
  root :to => "types#index"

  resources :types do
    resources :tasks
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :type

  validates_presence_of :name, :address, :phone_number, :website, :hours
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :businesses
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @type = Type.find(params[:type_id])
    @business = @type.businesses.new
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
    @type = Type.new
    render :index
  end

  def show
    @type = Type.find(params[:id])
    render :show
  end

  # def new
  #   @type = Type.new
  #   render :new
  # end

  def create
    @types = Type.all
    @type = Type.new(type_params)
    if @type.save
      redirect_to types_path
    else
      render :index
    end
  end

  def edit
    @type = Type.find(params[:id])
    render :edit
  end

  def update
    @type = Type.find(params[:id])
    if @type.update(type_params)
      redirect_to types_path
    else
      render :edit
    end
  end

  def destroy
    @type = Type.find(params[:id])
    @type.destroy
    redirect_to types_path
  end

  private
  def type_params
    params.require(:type).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/businesses/_form.html.erb
<%= render('layouts/errors', :object => @business) %>

<%= form_for [@type, @business] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :phone_number %>
<%= f.text_field :phone_number %>
<%= f.label :website %>
<%= f.text_field :website %>
<%= f.label :hours %>
<%= f.text_field :hours %>
<p><%= f.submit %></p>
<% end %>

app/views/businesses/new.html.erb
<h1>New business for <%= @type.name %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Oops there were some errors. Please try again:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikipages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/types/_form.html.erb
<%= render "layouts/errors", :object => @type %>

<%= form_for object do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/types/edit.html.erb
<h1>Edit Business Type</h1>

<%= render 'form', :object => @type %>

app/views/types/index.html.erb
<h1>Business Types</h1>

<%= render 'form', :object => @type %>

<ul>
  <% @types.each do |type| %>
    <li>
      <%= link_to type.name, type_path(type) %> -
      <%= link_to "Edit", edit_type_path(type) %> -
      <%= link_to "Delete", type_path(type), :data => {:confirm => "Are you sure?", :method => "delete"} %>
    </li>
  <% end %>
</ul>

<!-- <%= link_to "New Business Type", new_type_path %> -->

app/views/types/new.html.erb
<!-- <h1>New Business Type</h1>

<%= render 'form', :object => @type %> -->

app/views/types/show.html.erb
<h1><%= @type.name %></h1>

<% if @type.businesses.any? %>
<h4>Here are the businesses in this category:</h4>

<ul>
  <% @type.businesses.each do |business| %>
  <li>
    <%= business.name %> |
    <%= link_to "Edit", edit_type_business_path(@type, business) %> |
    <%= link_to "Delete", type_business_path(@type, business),
    :data => {:confirm => "Are you sure?",
      :method => "delete"} %>
    </li>
    <% end %>
  </ul>
  <% else %>
  <p>There are no businesses yet!</p>
  <% end %>

  <p><%= link_to "Add a business", new_type_business_path(@type) %></p>

<p>
  <%= link_to "Edit", edit_type_path(@type) %>
</p>
<p>
  <%= link_to "Delete", type_path(@type), :data => {:confirm => "Are you sure?", :method => "delete"} %>
</p>


<p>
  <%= link_to "Return to Business Types", types_path %>
</p>